### ISSUE TITLE
pin header distance

### ISSUE THREAD

**Issue by t-xigit** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800L#48]
[Here ](https://de.aliexpress.com/item/33045221960.html) is a drawing of the dimensions of the board.

However, I am designing a PCB with this board and there is no information of the distance between these two pin header rows.
![O1CN01EDGPdY2D7ReaXCUWe_!!2657898562](https://user-images.githubusercontent.com/15726945/74433519-d4aa9f00-4e60-11ea-9a4b-3e27f57933a6.png)

**Comment by Krezalis** [comment]
1.27mm

**Comment by t-xigit** [comment]
I don't mean the pitch of the header.
I mean the distance between the left and right header row.
Cheers

**Comment by maromme** [comment]
I got that if it helps. in width its about 10.5 x 2.54mm = 26.67mm

![Unbenannt](https://user-images.githubusercontent.com/60754017/74436127-328db580-4e66-11ea-82fd-3663a7120723.png)

If you are drwaing a footprint, I wold be grateful if you share it. Could need it myselfe.

**Comment by t-xigit** [comment]
@maromme here you go mate
[ttgo-t-call-v1_3.zip](https://github.com/Xinyuan-LilyGO/TTGO-T-Call/files/4198896/ttgo-t-call-v1_3.zip)

**Comment by maromme** [comment]
@t-xigit thank you very much. looks really good. looking forward to get my PCBs

**Comment by t-xigit** [comment]
@maromme 
Be careful with the orientation of the board.
There is a description in the footprint section.
Other than that this design was tested. Just the pins were off by 1.5 mm

**Comment by lewisxhe** [comment]
If there are still problems, please reopen the issue
