### ISSUE TITLE
Eagle/KiCAD Design files

### ISSUE THREAD

**Issue by SParishwad** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800L#61]
Could someone tell me if the Eagle/KiCAD design files exist? I don't know where to begin.

**Comment by t-xigit** [comment]
I shared the board outline here:
https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800L/issues/48

There are no ECAD Files only PDFs

**Comment by SParishwad** [comment]
Thanks.
