### ISSUE TITLE
Ground issues with GPRS and deepsleep

### ISSUE THREAD

**Issue by grichfitz** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800L#66]
Hya everyone,
I´m experiencing some strange issues with my project and I wondered if anyone else has experience of this.

My project goes into deepsleep and randomly gets wake up with ext1 from any of the pins I have assigned to ext1. Sometimes it gets into a fit and continues waking up.

The project is stable when there is no SIM and using Wifi.

Each of the wake up pins have 10k pulldown resistors.

I´m wondering if it a ground issue??

Any thoughts??

TIA

**Comment by lewisxhe** [comment]
What you need to check is your code, whether the used pins are used

**Comment by grichfitz** [comment]
Are you using a breadboard? I had similar issues of it waking up randomly, spent a week trying to diagnose. 
In the end having a 10k resistor directly connected from the same breadboard connection as the wake up pins to ground solved the problem. 
I use 12,13,14,15 and 25 for my wake up. What pins are you using?

**Comment by grichfitz** [comment]
This was solved in the end by making sure the 10k resistor was connected to the same connection in the breadboard as the GPIO pin, direct to gnd.
